#include <gtest/gtest.h>
#include <gmock/gmock.h>

#include "storage/csv_parser.hpp"
#include "storage/column_store.hpp"
#include "tests/common/test_utils.hpp"

#include <string>
#include <vector>
#include <sstream>

using namespace testing;
using namespace csv_test;

class CsvParserTest : public ::testing::Test {
protected:
    void SetUp() override {
        // Setup code
    }

    void TearDown() override {
        // Cleanup code
    }
};

TEST_F(CsvParserTest, ParsesEmptyString) {
    std::string empty_csv = "";
    ColumnStore store = csv::parse_csv(empty_csv);
    EXPECT_TRUE(store.column_names.empty());
    EXPECT_TRUE(store.columns.empty());
}

TEST_F(CsvParserTest, ParsesHeaderOnly) {
    std::string header_only_csv = "Col1,Col2,Col3";
    ColumnStore store = csv::parse_csv(header_only_csv);
    
    EXPECT_EQ(store.column_names.size(), 3);
    EXPECT_THAT(store.column_names, ElementsAre("Col1", "Col2", "Col3"));
    
    // Check each column exists but is empty
    for (const auto& name : store.column_names) {
        EXPECT_TRUE(store.columns.count(name) > 0);
        EXPECT_TRUE(store.columns.at(name).empty());
    }
}

TEST_F(CsvParserTest, ParsesSimpleCsv) {
    std::string simple_csv = "Col1,Col2,Col3\n1,2,3\n4,5,6";
    ColumnStore store = csv::parse_csv(simple_csv);
    
    // Check column names
    EXPECT_EQ(store.column_names.size(), 3);
    EXPECT_THAT(store.column_names, ElementsAre("Col1", "Col2", "Col3"));
    
    // Check column data
    EXPECT_EQ(store.columns.at("Col1").size(), 2);
    EXPECT_THAT(store.columns.at("Col1"), ElementsAre("1", "4"));
    EXPECT_THAT(store.columns.at("Col2"), ElementsAre("2", "5"));
    EXPECT_THAT(store.columns.at("Col3"), ElementsAre("3", "6"));
}

TEST_F(CsvParserTest, HandlesVaryingRowLengths) {
    // Some rows have more values than headers, others have fewer
    std::string varying_csv = "Col1,Col2,Col3\n1,2,3,4\n5,6";
    ColumnStore store = csv::parse_csv(varying_csv);
    
    // Check column names (should have 3)
    EXPECT_EQ(store.column_names.size(), 3);
    
    // First row has 4 values, but only first 3 should be used (because we have 3 column names)
    EXPECT_EQ(store.columns.at("Col1").size(), 2);
    EXPECT_EQ(store.columns.at("Col2").size(), 2);
    EXPECT_EQ(store.columns.at("Col3").size(), 2);
    
    // Last row has only 2 values, 3rd column should be empty string for that row
    EXPECT_EQ(store.columns.at("Col1")[1], "5");
    EXPECT_EQ(store.columns.at("Col2")[1], "6");
    EXPECT_EQ(store.columns.at("Col3")[1], ""); 
}

TEST_F(CsvParserTest, HandlesQuotedValues) {
    std::string quoted_csv = "Col1,Col2,Col3\n\"1\",\"hello, world\",\"3\"\n4,\"5\n5\",6";
    ColumnStore store = csv::parse_csv(quoted_csv);
    
    // Check column data with quoted values
    EXPECT_EQ(store.columns.at("Col1").size(), 2);
    EXPECT_EQ(store.columns.at("Col1")[0], "1");
    EXPECT_EQ(store.columns.at("Col2")[0], "hello, world"); // Comma inside quotes
    EXPECT_EQ(store.columns.at("Col2")[1], "5\n5");         // Newline inside quotes
}

TEST_F(CsvParserTest, HandlesEmptyCells) {
    std::string empty_cells_csv = "Col1,Col2,Col3\n1,,3\n,,6";
    ColumnStore store = csv::parse_csv(empty_cells_csv);
    
    // Check column data with empty cells
    EXPECT_EQ(store.columns.at("Col1").size(), 2);
    EXPECT_EQ(store.columns.at("Col1")[0], "1");
    EXPECT_EQ(store.columns.at("Col1")[1], "");
    EXPECT_EQ(store.columns.at("Col2")[0], "");
    EXPECT_EQ(store.columns.at("Col2")[1], "");
}

TEST_F(CsvParserTest, HandlesLargeCsv) {
    // Generate a larger CSV (not huge, but enough to test performance)
    std::string large_csv = TestDataGenerator::generateCsvString(1000, 10);
    ColumnStore store = csv::parse_csv(large_csv);
    
    // Check the size
    EXPECT_EQ(store.column_names.size(), 10);
    for (const auto& name : store.column_names) {
        EXPECT_EQ(store.columns.at(name).size(), 1000);
    }
}

TEST_F(CsvParserTest, HandlesUtf8Characters) {
    std::string utf8_csv = "Name,City\nJosé,München\n北京,こんにちは";
    ColumnStore store = csv::parse_csv(utf8_csv);
    
    // Check UTF-8 characters
    EXPECT_EQ(store.columns.at("Name").size(), 2);
    EXPECT_EQ(store.columns.at("Name")[0], "José");
    EXPECT_EQ(store.columns.at("City")[0], "München");
    EXPECT_EQ(store.columns.at("Name")[1], "北京");
    EXPECT_EQ(store.columns.at("City")[1], "こんにちは");
}

// Edge case: Malformed CSV
TEST_F(CsvParserTest, HandlesMalformedCsv) {
    // Unclosed quote
    std::string malformed_csv = "Col1,Col2\n\"unclosed quote,2";
    ColumnStore store = csv::parse_csv(malformed_csv);
    
    // The parser should make a best-effort attempt
    EXPECT_EQ(store.column_names.size(), 2);
    // The actual behavior may depend on the parser implementation
}

// Test with a file generated by the TestDataGenerator
TEST_F(CsvParserTest, ParsesGeneratedTestFile) {
    std::string filename = "tests/data/simple_test.csv";
    std::string csv_content = TestDataGenerator::createSimpleTestCsv(filename);
    
    // Parse the file content directly
    ColumnStore store_from_string = csv::parse_csv(csv_content);
    
    // Check column names
    EXPECT_EQ(store_from_string.column_names.size(), 3);
    EXPECT_THAT(store_from_string.column_names, ElementsAre("ID", "Value1", "Value2"));
    
    // Check data
    EXPECT_EQ(store_from_string.columns.at("ID").size(), 3);
    EXPECT_THAT(store_from_string.columns.at("ID"), ElementsAre("1", "2", "3"));
    EXPECT_THAT(store_from_string.columns.at("Value1"), ElementsAre("10", "20", "30"));
    EXPECT_THAT(store_from_string.columns.at("Value2"), ElementsAre("100", "200", "300"));
}

// Edge cases test file
TEST_F(CsvParserTest, ParsesEdgeCaseTestFile) {
    std::string filename = "tests/data/edge_case_test.csv";
    std::string csv_content = TestDataGenerator::createEdgeCaseTestCsv(filename);
    
    ColumnStore store = csv::parse_csv(csv_content);
    
    // Check column names
    EXPECT_EQ(store.column_names.size(), 4);
    
    // Check specific edge cases
    EXPECT_EQ(store.columns.at("Text")[0], "Quoted text");
    EXPECT_EQ(store.columns.at("Text")[1], ""); // Empty cell
    EXPECT_EQ(store.columns.at("Text")[2], "Text with, comma");
    EXPECT_EQ(store.columns.at("Text")[3], "Line\nbreak");
    EXPECT_EQ(store.columns.at("Text")[4], "\"Double quotes\"");
}
