// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: csv_service.proto

#include "csv_service.pb.h"
#include "csv_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace csvservice {

static const char* CsvService_method_names[] = {
  "/csvservice.CsvService/UploadCsv",
  "/csvservice.CsvService/ListLoadedFiles",
};

std::unique_ptr< CsvService::Stub> CsvService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CsvService::Stub> stub(new CsvService::Stub(channel, options));
  return stub;
}

CsvService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_UploadCsv_(CsvService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListLoadedFiles_(CsvService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CsvService::Stub::UploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::csvservice::CsvUploadResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::csvservice::CsvUploadRequest, ::csvservice::CsvUploadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UploadCsv_, context, request, response);
}

void CsvService::Stub::async::UploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest* request, ::csvservice::CsvUploadResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::csvservice::CsvUploadRequest, ::csvservice::CsvUploadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UploadCsv_, context, request, response, std::move(f));
}

void CsvService::Stub::async::UploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest* request, ::csvservice::CsvUploadResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UploadCsv_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::csvservice::CsvUploadResponse>* CsvService::Stub::PrepareAsyncUploadCsvRaw(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::csvservice::CsvUploadResponse, ::csvservice::CsvUploadRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UploadCsv_, context, request);
}

::grpc::ClientAsyncResponseReader< ::csvservice::CsvUploadResponse>* CsvService::Stub::AsyncUploadCsvRaw(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUploadCsvRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CsvService::Stub::ListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::csvservice::CsvFileList* response) {
  return ::grpc::internal::BlockingUnaryCall< ::csvservice::Empty, ::csvservice::CsvFileList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListLoadedFiles_, context, request, response);
}

void CsvService::Stub::async::ListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty* request, ::csvservice::CsvFileList* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::csvservice::Empty, ::csvservice::CsvFileList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListLoadedFiles_, context, request, response, std::move(f));
}

void CsvService::Stub::async::ListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty* request, ::csvservice::CsvFileList* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListLoadedFiles_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::csvservice::CsvFileList>* CsvService::Stub::PrepareAsyncListLoadedFilesRaw(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::csvservice::CsvFileList, ::csvservice::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListLoadedFiles_, context, request);
}

::grpc::ClientAsyncResponseReader< ::csvservice::CsvFileList>* CsvService::Stub::AsyncListLoadedFilesRaw(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListLoadedFilesRaw(context, request, cq);
  result->StartCall();
  return result;
}

CsvService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CsvService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CsvService::Service, ::csvservice::CsvUploadRequest, ::csvservice::CsvUploadResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CsvService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::csvservice::CsvUploadRequest* req,
             ::csvservice::CsvUploadResponse* resp) {
               return service->UploadCsv(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CsvService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CsvService::Service, ::csvservice::Empty, ::csvservice::CsvFileList, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CsvService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::csvservice::Empty* req,
             ::csvservice::CsvFileList* resp) {
               return service->ListLoadedFiles(ctx, req, resp);
             }, this)));
}

CsvService::Service::~Service() {
}

::grpc::Status CsvService::Service::UploadCsv(::grpc::ServerContext* context, const ::csvservice::CsvUploadRequest* request, ::csvservice::CsvUploadResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CsvService::Service::ListLoadedFiles(::grpc::ServerContext* context, const ::csvservice::Empty* request, ::csvservice::CsvFileList* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace csvservice

