// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: csv_service.proto
// Original file comments:
// csv_service.proto
#ifndef GRPC_csv_5fservice_2eproto__INCLUDED
#define GRPC_csv_5fservice_2eproto__INCLUDED

#include "csv_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace csvservice {

class CsvService final {
 public:
  static constexpr char const* service_full_name() {
    return "csvservice.CsvService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status UploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::csvservice::CsvUploadResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvUploadResponse>> AsyncUploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvUploadResponse>>(AsyncUploadCsvRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvUploadResponse>> PrepareAsyncUploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvUploadResponse>>(PrepareAsyncUploadCsvRaw(context, request, cq));
    }
    virtual ::grpc::Status ListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::csvservice::CsvFileList* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvFileList>> AsyncListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvFileList>>(AsyncListLoadedFilesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvFileList>> PrepareAsyncListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvFileList>>(PrepareAsyncListLoadedFilesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void UploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest* request, ::csvservice::CsvUploadResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void UploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest* request, ::csvservice::CsvUploadResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty* request, ::csvservice::CsvFileList* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty* request, ::csvservice::CsvFileList* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvUploadResponse>* AsyncUploadCsvRaw(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvUploadResponse>* PrepareAsyncUploadCsvRaw(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvFileList>* AsyncListLoadedFilesRaw(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::csvservice::CsvFileList>* PrepareAsyncListLoadedFilesRaw(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status UploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::csvservice::CsvUploadResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csvservice::CsvUploadResponse>> AsyncUploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csvservice::CsvUploadResponse>>(AsyncUploadCsvRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csvservice::CsvUploadResponse>> PrepareAsyncUploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csvservice::CsvUploadResponse>>(PrepareAsyncUploadCsvRaw(context, request, cq));
    }
    ::grpc::Status ListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::csvservice::CsvFileList* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csvservice::CsvFileList>> AsyncListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csvservice::CsvFileList>>(AsyncListLoadedFilesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csvservice::CsvFileList>> PrepareAsyncListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::csvservice::CsvFileList>>(PrepareAsyncListLoadedFilesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void UploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest* request, ::csvservice::CsvUploadResponse* response, std::function<void(::grpc::Status)>) override;
      void UploadCsv(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest* request, ::csvservice::CsvUploadResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty* request, ::csvservice::CsvFileList* response, std::function<void(::grpc::Status)>) override;
      void ListLoadedFiles(::grpc::ClientContext* context, const ::csvservice::Empty* request, ::csvservice::CsvFileList* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::csvservice::CsvUploadResponse>* AsyncUploadCsvRaw(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::csvservice::CsvUploadResponse>* PrepareAsyncUploadCsvRaw(::grpc::ClientContext* context, const ::csvservice::CsvUploadRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::csvservice::CsvFileList>* AsyncListLoadedFilesRaw(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::csvservice::CsvFileList>* PrepareAsyncListLoadedFilesRaw(::grpc::ClientContext* context, const ::csvservice::Empty& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_UploadCsv_;
    const ::grpc::internal::RpcMethod rpcmethod_ListLoadedFiles_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status UploadCsv(::grpc::ServerContext* context, const ::csvservice::CsvUploadRequest* request, ::csvservice::CsvUploadResponse* response);
    virtual ::grpc::Status ListLoadedFiles(::grpc::ServerContext* context, const ::csvservice::Empty* request, ::csvservice::CsvFileList* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_UploadCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_UploadCsv() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_UploadCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadCsv(::grpc::ServerContext* /*context*/, const ::csvservice::CsvUploadRequest* /*request*/, ::csvservice::CsvUploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadCsv(::grpc::ServerContext* context, ::csvservice::CsvUploadRequest* request, ::grpc::ServerAsyncResponseWriter< ::csvservice::CsvUploadResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListLoadedFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListLoadedFiles() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListLoadedFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListLoadedFiles(::grpc::ServerContext* /*context*/, const ::csvservice::Empty* /*request*/, ::csvservice::CsvFileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListLoadedFiles(::grpc::ServerContext* context, ::csvservice::Empty* request, ::grpc::ServerAsyncResponseWriter< ::csvservice::CsvFileList>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_UploadCsv<WithAsyncMethod_ListLoadedFiles<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_UploadCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_UploadCsv() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::csvservice::CsvUploadRequest, ::csvservice::CsvUploadResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::csvservice::CsvUploadRequest* request, ::csvservice::CsvUploadResponse* response) { return this->UploadCsv(context, request, response); }));}
    void SetMessageAllocatorFor_UploadCsv(
        ::grpc::MessageAllocator< ::csvservice::CsvUploadRequest, ::csvservice::CsvUploadResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::csvservice::CsvUploadRequest, ::csvservice::CsvUploadResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_UploadCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadCsv(::grpc::ServerContext* /*context*/, const ::csvservice::CsvUploadRequest* /*request*/, ::csvservice::CsvUploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UploadCsv(
      ::grpc::CallbackServerContext* /*context*/, const ::csvservice::CsvUploadRequest* /*request*/, ::csvservice::CsvUploadResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListLoadedFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListLoadedFiles() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::csvservice::Empty, ::csvservice::CsvFileList>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::csvservice::Empty* request, ::csvservice::CsvFileList* response) { return this->ListLoadedFiles(context, request, response); }));}
    void SetMessageAllocatorFor_ListLoadedFiles(
        ::grpc::MessageAllocator< ::csvservice::Empty, ::csvservice::CsvFileList>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::csvservice::Empty, ::csvservice::CsvFileList>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListLoadedFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListLoadedFiles(::grpc::ServerContext* /*context*/, const ::csvservice::Empty* /*request*/, ::csvservice::CsvFileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListLoadedFiles(
      ::grpc::CallbackServerContext* /*context*/, const ::csvservice::Empty* /*request*/, ::csvservice::CsvFileList* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_UploadCsv<WithCallbackMethod_ListLoadedFiles<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_UploadCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_UploadCsv() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_UploadCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadCsv(::grpc::ServerContext* /*context*/, const ::csvservice::CsvUploadRequest* /*request*/, ::csvservice::CsvUploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListLoadedFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListLoadedFiles() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListLoadedFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListLoadedFiles(::grpc::ServerContext* /*context*/, const ::csvservice::Empty* /*request*/, ::csvservice::CsvFileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_UploadCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_UploadCsv() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_UploadCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadCsv(::grpc::ServerContext* /*context*/, const ::csvservice::CsvUploadRequest* /*request*/, ::csvservice::CsvUploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestUploadCsv(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListLoadedFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListLoadedFiles() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListLoadedFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListLoadedFiles(::grpc::ServerContext* /*context*/, const ::csvservice::Empty* /*request*/, ::csvservice::CsvFileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListLoadedFiles(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_UploadCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_UploadCsv() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->UploadCsv(context, request, response); }));
    }
    ~WithRawCallbackMethod_UploadCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status UploadCsv(::grpc::ServerContext* /*context*/, const ::csvservice::CsvUploadRequest* /*request*/, ::csvservice::CsvUploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* UploadCsv(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListLoadedFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListLoadedFiles() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListLoadedFiles(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListLoadedFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListLoadedFiles(::grpc::ServerContext* /*context*/, const ::csvservice::Empty* /*request*/, ::csvservice::CsvFileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListLoadedFiles(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_UploadCsv : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_UploadCsv() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::csvservice::CsvUploadRequest, ::csvservice::CsvUploadResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::csvservice::CsvUploadRequest, ::csvservice::CsvUploadResponse>* streamer) {
                       return this->StreamedUploadCsv(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_UploadCsv() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status UploadCsv(::grpc::ServerContext* /*context*/, const ::csvservice::CsvUploadRequest* /*request*/, ::csvservice::CsvUploadResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedUploadCsv(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::csvservice::CsvUploadRequest,::csvservice::CsvUploadResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListLoadedFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListLoadedFiles() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::csvservice::Empty, ::csvservice::CsvFileList>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::csvservice::Empty, ::csvservice::CsvFileList>* streamer) {
                       return this->StreamedListLoadedFiles(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListLoadedFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListLoadedFiles(::grpc::ServerContext* /*context*/, const ::csvservice::Empty* /*request*/, ::csvservice::CsvFileList* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListLoadedFiles(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::csvservice::Empty,::csvservice::CsvFileList>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_UploadCsv<WithStreamedUnaryMethod_ListLoadedFiles<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_UploadCsv<WithStreamedUnaryMethod_ListLoadedFiles<Service > > StreamedService;
};

}  // namespace csvservice


#endif  // GRPC_csv_5fservice_2eproto__INCLUDED
